### PR TITLE
refactor(): switch to monorepo + lerna

### PR DESCRIPTION
**Pull request by kaosat-dev**
WORK in progress ! DO NOT MERGE !! 
This PR introduces some big structural changes
* split up code internally into sub package that can be reused
    * all web ui code is now in packages/web
    * all CLI code is now in packages/cli
    * all common/ core code is now in packages/core
    * all examples are now in packages/examples
* use of Lerna as a way to manage the monorep (just like in our IO repostiory)

This is done in order to:
* to enable us to share code more easily between the various variants of jscad (web, cli, desktop)
* to have smaller/dedicated npm packages for CLI/web etc
* to enable us to manage the complexity better

@z3dev @jtoy  @danmarshall  , you might be interested in these changes.

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Does your submission pass tests?

### CODE REVIEW

**Comment by z3dev** [comment]
A few small things...
- cp ../examples ./examples ==> cp -r ../examples ./examples in readme files

**Comment by z3dev** [comment]
Website with Chrome
- SVG drag and drop is not working, failing with exception

**Comment by z3dev** [comment]
Website with Safari
- SVG drag and drop is not working, failing with... TypeError: obj is not an Object. (evaluating ''id' in obj') Line: 13895,col: 19

**Comment by kaosat-dev** [comment]
thanks for the tests @z3dev !
- could you clarify about `examples` ? not sure I understand
- about the site not working with svg will take a look (is it working ok in the current online version ?)

**Pull request merged**
