### PR TITLE
feat(modeling): remove extrudeRectangular

### PR DESCRIPTION
**Pull request by platypii**
This might be controversial. Let's use this PR for discussion on removing `extrudeRectangular` from V3.

The `extrudeRectangular` function is supposed to:

> Extrude the given geometry by following the outline(s) with a rectangle.

But it's not doing that. If you "follow the outline(s) with a rectangle" you would get something more like the red shape, but `extrudeRectangular` returns the shape on the right:

extrude-rect

In reality `extrudeRectangular` is basically just doing:

```js
extrudeLinear({}, offset({}, geometry))
```

This is not easy to fix, so I suggest that we simply delete `extrudeRectangular`. I would be surprised if anyone is using it, but if they are, they can use `offset`+`extrude` instead.

I think what was really intended here was a `stroke` function like the suggestion in #1272 

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Does your submission pass tests?

### CODE REVIEW

**Comment by z3dev** [comment]
@platypii interesting. i really didn't like this extrude function from day one as, as you mentioned, is just putting two functions together. users should be able to figure out how to do this through a simple example.

i also don't like 'torus' either, as that is simply extrude rotate with a sphere. it makes no sense to implement primitives via complex functionality. primitive should exist by themselves. examples should show how to create a torus.

**Comment by platypii** [comment]
Rebased to fix merge conflicts.

Can anyone tell me what exactly is "rectangular" about `extrudeRectangular`?

**Comment by z3dev** [comment]
> Rebased to fix merge conflicts.
> 
> Can anyone tell me what exactly is "rectangular" about `extrudeRectangular`?

Nope. You could go back and look at V1, which may have had the same issues, or different issues.

**Comment by z3dev** [comment]
From CSG.js V1... math/Path2.js

```
// Expand the path to a CAG
// This traces the path with a circle with radius pathradius
expandToCAG: function (pathradius, resolution) {
}
```

**Comment by platypii** [comment]
Earliest I could find was this commit from 2012: [joostn/OpenJsCad@b059ed95](https://github.com/joostn/OpenJsCad/commit/b059ed95#diff-77464d6f63d562f0ddd14d2cbdef2eea956b7f1e2fe26ef270b9b5bb88768619R3652-R3667)

So... can we kill it? :fire:

**Review by z3dev — APPROVED** [review]

**Pull request merged**
