### PR TITLE
V2

### PR DESCRIPTION
**Pull request by EricBuijs**
### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [ ] Does your submission pass tests?

> Note: please do NOT include build files (those generate by the build-xxx commands) with your PR,

Thank you for your help in advance, much appreciated !

### CODE REVIEW

**Comment by EricBuijs** [comment]
As a first result I create a landingpage. I hope I used the correct procedures for this pull request but if I didn't I'm sure you guys will tell me.

**Comment by kaosat-dev** [comment]
looking good at first glance @EricBuijs ! thanks a lot !
I will take it for a spin locally tomorrow :)

**Comment by EricBuijs** [comment]
Maybe it's good to point out that I used only four colors throughout. The first are the two indicated by Mark: #e34a96 (Magenta) and #4ae3c3 (green-blue). These colors are complemented by #fff (white) and #444 (grey).

**Comment by kaosat-dev** [comment]
@EricBuijs sorry for the slow reply ! So I took it for a spin , and overall it is a great start !
I think we will need to tweak a few of the colors and minor details but it is solid ! thanks a lot !
The only thing that really threw me off is what I think is the placeholder for the main image  ? (that weird transparent one)

**Comment by kaosat-dev** [comment]
Small note: next time please create a specific branch off of V2 instead of using it directly : like so
- git checkout V2 // based on V2
- git checkout -b <your-branch-name>

**Comment by EricBuijs** [comment]
@kaosat-dev What would be the recommend way forward? Normally I would do responsiveness next and then work towards finalizing the landing page because it pretty much defines the theme of the website. I would also like to add an embedded example, other examples and howtos. Can someone give me some pointers on this? Even further down the road I'll add other pages but those need input on what we want to do with docs, features and community etc. Or is that beyond the scope of this part of the development of the V2 website?

I'm currently pretty busy but hopefully next week I'll be able to do an additional push.

**Comment by kaosat-dev** [comment]
@EricBuijs very sorry for the slow reply, health & computer issues :) 
- For the embeded example I think you should be able to use this https://github.com/jscad/OpenJSCAD.org/blob/V2/packages/web/demo.html directly, but if changes are needed, I can look into it after next Wednesday (replacement computer).
- examples: for now we will have to go with the current ones for now
- howtos: I am drawing a blank but I'll get cranking !
- other pages: we are almost ready for the new forums, so we should be able to squeeze that one in ?

**Comment by EricBuijs** [comment]
@kaosat-dev 

- I'll take a better look at the embedded example later this week. But I suppose this is not a problem.
- Excellent. The're plenty on the current OpenJSCAD website. I'm thinking about some (three?) example highlights for the landing page and the rest on another page. This to avoid cluttering.
- Ok, I'll also look around on the internet for howto's.
- Great news about the forum. What do you guys plan on using?

I'll move forward with the landing page and add responsiveness and the embedded example. Is it a good idea to merge my pull request so that I can create a new one?

**Comment by z3dev** [comment]
For the how to notes...
- maybe we could pick out the top three ... how do I ... questions
- split up the work, and draw up some outlines
- discuss, and come up with a common format
- develope the content
- let @EricBuijs meld the content into the site

It’s probably a whole lot harder then that. 😃

**Comment by kaosat-dev** [comment]
@EricBuijs sorry for the slow reply, I think we can merge this one and build from there , agreed ?

**Comment by z3dev** [comment]
Sure. How about making a branch for website content? Then @EricBuijs and others to work contribute without worry.

**Comment by kaosat-dev** [comment]
merging this one @EricBuijs ! we can resume in another PR ! Verry sorry for the delay !

**Comment by EricBuijs** [comment]
@kaosat-dev The coming two weeks I finally have time to do additional work on this project.

**Pull request merged**
