### PR TITLE
feat(modeling): rework math objects to conform with gl-matrix

### PR DESCRIPTION
**Pull request by z3dev**
**BIG CHANGES!**

These changes adjust the math objects to the same API as gl-matrix. This should have the following affects
- improved performance as API signatures are now fixed (no more ...params)
- improved performance in the use of math objects (less allocations)
- improved interoperability with gl-matrix (no need to learn a different API)

NOTE: Optimizations of code was a natural outcome of these changes. Further optimization is still possible.

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Does your submission pass tests?

### CODE REVIEW

**Comment by z3dev** [comment]
Here are the first set of performance statistics for these changes. Very nice!

For those following, take a look at intersection, subtract, and union performance.

[JSCADPerformance20310427.pdf](https://github.com/jscad/OpenJSCAD.org/files/6382323/JSCADPerformance20310427.pdf)

There does seem to be a regression in measureVolume(). :(

**Comment by z3dev** [comment]
> There does seem to be a regression in measureVolume(). :(

Hmm... Why 10000 test is faster than 100000 test as well? Strangeness.
Relatively speaking in TIME, measureVolume() is still very fast.

**Review by SimonClark — COMMENTED** [review]
Scanned through as best as I could.  Changes look reasonable and well considered.  Nice!

**Comment by z3dev** [comment]
> Scanned through as best as I could. Changes look reasonable and well considered. Nice!

Yeah. It's a big set of changes. Thanks.

I'm still running performance tests as there were some issues with the extrusions. I should have some nice statistics at this end of this week.

**Review by mister-jscad — APPROVED** [review]
Review everything again. Looks fine.

Make sure the examples work 100%.

**Review by mister-jscad — APPROVED** [review]
Good to go. Thanks for late changes.

**Pull request merged**
