### PR TITLE
Elliptic cylinder

### PR DESCRIPTION
**Pull request by Przemyslaw-Marchewka**
I was missing this type of shape. Scaling normal cylinder will not give me te same effect (look into example in function doc). This is my first commit to a public repo, so please review ! 

This is a copy of normal cylinder function with following changes:
- point function - new math
- if statements in validation and loop part

Performed tests:
- used in complex project
- netfabb validation
- curved cylinder

### CODE REVIEW

**Comment by Spiritdude** [comment]
Let comment, just to be sure you don't miss it (or I miss it): all changes to csg.js should be submitted to https://github.com/joostn/OpenJsCad/tree/gh-pages which will be backported here. It's not ideal but this way the mother project leads the way for csg.js and OpenJSCAD follows in that regards of csg.js.

Cc: @z3dev

**Comment by z3dev** [comment]
@Przemyslaw-Marchewka  An example of the JSCAD script would be very helpful.

**Comment by dav-m85** [comment]
@Spiritdude @z3dev is backporting from OpenJsCad still the rule ? If yes, I would gladly reopen this PR at the right place.

**Comment by z3dev** [comment]
Yes, please.

**Comment by dav-m85** [comment]
Reopened here: https://github.com/joostn/OpenJsCad/pull/89. I kept @Przemyslaw-Marchewka as author of the commit of course.

**Comment by z3dev** [comment]
This PR was move and merged as part of the CSG.js library. Closing here.

**Pull request closed without merging**
