### PR TITLE
Fix typo in rotate function

### PR DESCRIPTION
**Pull request by minatani**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [ ] Does your submission pass tests?

> Note: please do NOT include build files (those generate by the build-xxx commands) with your PR,

Thank you for your help in advance, much appreciated !
Fix minor typo in rotate() function's comment. 45 degrees has been converted to radians. Currently, deg2rad() function is not available.

### CODE REVIEW

**Comment by z3dev** [comment]
@minatani please revert the change to README, as there's another pull request in progress for changes to README files.

**Comment by kaosat-dev** [comment]
Even better, please rebase off of V2 directly, you have a lot of extra commits from V1 :)

**Comment by z3dev** [comment]
@minatani thanks for the change. i have put your documentation changes into PR #563 

please close this pull request

**Comment by minatani** [comment]
Thank you. Sorry I had made a PR with unintentional changes.

**Comment by kaosat-dev** [comment]
no worries @minatani :) thanks for the fix

**Pull request closed without merging**
