### PR TITLE
feat(all): Overhaul and V2 groundwork

### LINKED ISSUE #119: Enhancement: Allow Multiple Processers per Page
At this time (version 0.3.*), there can only be one (1) processor due to the requirement of specific HTML document requirements, e.g. div with id='errordiv'. It would be better to search the parent of the viewer div for specific classes of HTML elements.

Obtain the parent HTML element of the viewer
Search for HTML element 'div' with class 'errordiv'
etc

### LINKED ISSUE #137: smooth lighting
I am sure [you are aware](https://github.com/Spiritdude/OpenJSCAD.org/blob/adc37e44a6df1074581983a22be9f21cdc072ade/openjscad.js#L507) of smooth lighting problems. Well, I have been fixing them in the project that is basically private fork of your code. Although I cannot just copy the code over here, I can describe what I did. 1st, you have the bug [here](https://github.com/Spiritdude/OpenJSCAD.org/blob/adc37e44a6df1074581983a22be9f21cdc072ade/openjscad.js#L527) - it should check the color against colors[vertexindex], or else colors are interpolated. 2nd, you want to add different colors to CSG primitives' surfaces (such as cylinder top, bottom and side), and 3rd you want to make sure these colors are never the same, e g [here](https://github.com/Spiritdude/OpenJSCAD.org/blob/adc37e44a6df1074581983a22be9f21cdc072ade/openscad.js#L344) you set the same color for the whole surface, and that effectively merges all cut surfaces. I hacked around it by re-using existing "shared"-s on polygons, but you need to think of better solution to all this, and then you will have this kind of shading:

screen shot 2016-02-24 at 23 54 20

### LINKED ISSUE #167: Object size, zoom and clipping (units and documentation)
An object with length 800 (I would like to use millimeters, so 800 mm = 80 cm = 0.8 m, about 31") is clipped at about half that once zoomed out to full extent:

```
function main() {
   return cube({size: [400,800,28], center: true});
}
```

What are the limits to the object size? 

On a related note: [the documentation](https://en.wikibooks.org/wiki/OpenJSCAD_User_Guide) does not seem to include anything about real-world units.

### LINKED ISSUE #235: Where are the basic view alignment functions?
Hi, 

I'm in transition to OpenJSCAD. 
OpenSCAD has basic view alignment functions: Right, Top, Bottom, Front, and Back. I use these features whenever I design mechanical parts that require precise positioning.

I found OpenJSCAD doesn't have them or are there built-in hotkeys already?

### LINKED ISSUE #245: Proposal: switch to a real module system for better modular designs
## Curent system
Hi everyone ! right now we are using a custom and rather limited `include` system to enable modular design & part reuse, with a few major flaws:
### pros
- simple
- custom
### cons
- **reinventing the wheel**: all the issues we face have already been solved elsewhere, better
- **global pollution** : all variables declared in ANY `include()` are pushed to the global scope 
- **unclear syntax** for export & import : ie what is exported ?? what if we have mutlple functions with the same name in different modules etc (hint, not possible)
```javascript
const someValue = 42
const someText = 'foo'
coolPart = function() { 
   return cube({size:someValue}).union(text(someText)
}
```
- non idiomatic : the syntax teaches bad practices
- no relative path resolution
- greedy evaluation : any code in an imported module is immediatly evaluated & run (careful what you import!)
- not integrated with the rest of the javascript ecosystem

## Proposal
The node.js & js ecosystem have been **very** successfully using modules for years, let's use that tech and knowledge to our advantage : 
> Note: this applies to both common.js & es6 modules as well
### pros 
(in addition to all the cons of the current system, which are all resolved in commonjs/es6 modules)
- clear , explicit and proven syntax : 
export: (coolPart.jscad)
```javascript
const someValue = 42
const someText = 'foo' // this one is not exported, yet still available at the module level

function coolPart(){
  return cube({size:someValue}).union(text(someText)
}
module.exports = { //these are exported and available from any consumer
  someValue,
  coolPart
}
```
import
```javascript
const {coolPart} = require('./coolPart.jscad') //we can selectively import features, etc
```
- all the existing javascript packages & tools at our disposal
- simpler to distribute package and use them (distribution with current syntax is not problematic, but use is)
- OpenJSCAD is javascript, we should embrace it , instead of half heartedly hiding it :)
### cons 
- higher complexity in browser (but less in node.js),  there are [many](http://requirebin.com/) [open source](https://github.com/maxogden/requirebin) [tools](https://www.webpackbin.com/) to code with modules in the browsers, they can be self hosted , but is more complex. 
>note: the commonjs require function / module loading is very simple and could also be emulated for a limited browser use
- possible dependency issues (as in , too much)

Of course this could be rolled out progressively, tested & tried, and would not need to impact the current implementation of include. 

As you can likely see, I am quite passionate about the subject .
Any thoughts ?

### LINKED ISSUE #321: Feature: add axis indicators to the 3d view
## Expected Behavior
Being able to tell which way is +/- x/y/z axis.
It is very confusing to navigate the 3d view and do correct modelling without clearly indicated axis.
I will be adding this feature asap

## Actual Behavior
No indicator

## Steps to Reproduce the Problem
1 . start openjscad
2. see there is not axis indicator

## Specifications

  - Environment: browser

### LINKED ISSUE #327: Support multiple languages
## Expected Behavior
The language of the page is now only English. There are other languages in this world, and support for other languages would be very nice.

## Actual Behavior
The language of the page is now only English.

## Steps to Reproduce the Problem

  1. Set browser language to German
  2. Load the website
  3. Language of website is English

## Specifications

  - Version: Any
  - Platform: Any
  - Environment: Any browser

### LINKED ISSUE #336: Decouple mouse events from Viewer
I know @kaosat-dev is working on a new Viewer, so I'm voting for a new feature :)
I'd like the mouse events to be decoupled from the Viewer, so that I can control the camera with other sensors. Here's a couple of ideas of how I'd like to control the camera:
* with the device accelerometer
* via scroll position
* via mousemove, without button

At the very least, it would be good to have an option to disable mouse listeners. Even better would be to decouple it so that the mouse event code is not in the JS for a Viewer.

### LINKED ISSUE #343: Embedding 1.6.1
I've used openjscad as an embedded feature on my website for a number of years, but the version I was using was very old (I'm not sure which one, but [here's a link to the source](http://www.cgtk.co.uk/lib/openjscad/openjscad.js) - it has a couple of small modifications for viewer size control).  Examples of the embedded versions using the old openjscad are [Grinder Gauges](http://www.cgtk.co.uk/metalwork/grinder/gauges) and [Lathe Threading Gauges](http://www.cgtk.co.uk/metalwork/minilathe/threadgauges).

I'm now using 1.6.1 on [this page](http://www.cgtk.co.uk/metalwork/reference/toolgrinding), but getting it working took me quite a lot of hours and was very frustrating.

## Expected Behaviour

I expected to be able to embed openjscad 1.6.1 on a website and customise settings such as whether the "plate" or the axes are shown.  I also expected the size of the `viewerContext` to affect the size of the canvas and not for it to be made about 25% wider and only 13 pixels high.

## Actual Behaviour - First Problem

When I set up the openjscad 1.6.1 viewer (`dist/opt.js`) on my web server, the canvas wasn't viewable.  After a lot of hacking around, I found that `LightGLEngine.prototype`'s `init()` declaration wasn't doing what I would expect it to do.  This is the patch I applied - the original `this.containerEl.width` was returning `undefined`.  I initially changed it to `this.containerEl.style.width` but this didn't seem to work (maybe something to do with `containerEl` having it's width set to `100%` rather than a `px` value in `Processor.createElements`?)

```diff
--- a/static/libraries/openjscad/1.6.1/opt.js
+++ b/static/libraries/openjscad/1.6.1/opt.js
@@ -40779,8 +40765,13 @@
 LightGLEngine.prototype = {
   init: function init() {
     // set initial canvas size
-    this.gl.canvas.width = this.containerEl.width;
-    this.gl.canvas.height = this.containerEl.height;
+    // ASB: This doesn't seem to work as released,
+    // ASB: (should be style.width but even then it
+    // ASB: gets 100% instead of an actual value).
+    //this.gl.canvas.width = this.containerEl.width;
+    //this.gl.canvas.height = this.containerEl.height;
+    this.gl.canvas.width = this.containerEl.parentNode.clientWidth;
+    this.gl.canvas.height = this.containerEl.parentNode.clientHeight;

     this.handleResize();
   },
```

## Actual Behaviour - Second Problem

I also had a problem with the `resizeCanvas` function as it was taking my fixed pixel size (690 pixels in this case) and multiplying it by 1.25 as that was what Chrome was returning as the `devicePixelRatio`.  I fixed this by forcing `devicePixelRatio` to be 1.  Now I must admit that this was done at the same time as the above, so it could be that fixing the one above makes the following unnecessary, but I'm happy with it at the moment and don't want to break my working version!

```diff
--- a/static/libraries/openjscad/1.6.1/opt.js
+++ b/static/libraries/openjscad/1.6.1/opt.js
@@ -41371,7 +41362,8 @@
   resizeCanvas: function resizeCanvas() {
     var canvas = this.canvas;

-    var devicePixelRatio = window.devicePixelRatio || 1;
+      // ASB: Changed pixel ratio to 1
+    var devicePixelRatio = 1; //window.devicePixelRatio || 1;
     canvas.width = this.containerEl.clientWidth * devicePixelRatio;
     canvas.height = this.containerEl.clientHeight * devicePixelRatio;
   },
```

## Actual Behaviour - Third Problem

As I was reading `opts.js`, I saw a comment in the Viewer function: "see the defaults method on how to change these".  As I was looking to change the settings, I went to the defaults method, but was none the wiser as it wasn't at all clear.  I'm sure I could hack the code and change the defaults, but I hoped this would be more of a library and I could have a single instance of `opts.js` on my web server and adjust the settings on each page that has a model.  After many hours of searching, I gave up in this and did the following hacks in order to make it possible:

```diff
--- a/static/libraries/openjscad/1.6.1/opt.js
+++ b/static/libraries/openjscad/1.6.1/opt.js
@@ -40647,21 +40647,7 @@
   var viewer = document.getElementById('viewerContext');
   var design = viewer.getAttribute('design-url');

-  gProcessor = new Processor(viewer, { viewer: { plate: { size: 1000,
-        m: { i: 1,
-          color: { r: 0.8, g: 0.8, b: 0.8, a: 0.5 }
-        },
-        M: { i: 100,
-          color: { r: 0.5, g: 0.5, b: 0.5, a: 0.5 }
-        }
-      },
-      camera: { position: { x: 0, y: 0, z: 1000 },
-        clip: { min: 0.5, max: 3000 }
-      },
-      axis: { draw: true
-      }
-    }
-  });
+  gProcessor = new Processor(viewer);

   // load the given design
   if (design) {
@@ -41447,6 +41439,16 @@
   }
 };

+// ASB: Added rather hacky method of customising settings
+//      as I couldn't find a supported way of doing so.
+if (typeof(viewerCustomisation) == "function") {
+    Viewer = viewerCustomisation(Viewer);
+}
+else {
+    console.log("No viewer customisation");
+}
+
+
 module.exports = Viewer;

 },{"./jscad-viewer-helpers":380,"./jscad-viewer-lightgl":381}],383:[function(require,module,exports){
```

Then in my main html file, I added:

```html
<script type="text/javascript">
       function viewerCustomisation(Viewer) {
               var standard_defaults = Viewer.defaults();
               Viewer.defaults = function() {
                       var mydefaults = jQuery.extend(true, {}, standard_defaults);
                       mydefaults['axis']['draw'] = false;
                       mydefaults['plate']['draw'] = false;
                       mydefaults['camera']['position']['z'] = 250;
                       return mydefaults;
               };
               return Viewer;
       }
</script>
```

I'm **sure** there must be a better way of doing this, but `Viewer` isn't accessible outside the script (due to the `browserify` magic) and I couldn't find any documentation anywhere on how to do this.

Please accept my apologies if I've been missing a really obvious wiki page that explains all of this.

## Specifications

  - Version: 1.6.1
  - Platform: My website (details above)
  - Environment: Custom web server, Google Chrome on Windows 10

### LINKED ISSUE #344: Proposal : simple api for embeded version
Given the difficulties currently to embed and configure OpenJSCAD I have following proposal for an upcoming version: 
A simple api to use for simple embeding : a single function, something like this

```javascript
// initialize
const initialOptions = {
  viewer : {camera:{xxx}},
  useBackgroundWorkers: true
}
const jscad = makeJscad(initialOptions)
// define your script
const yourSuperDesignScript = 'function main() { }'

// set parameters live , call this from callback/whatever
jscad({script: yourSuperDesignScript})
```

### LINKED ISSUE #364: Enhancement:  provide ability to set global (world) background color of drawing workspace
Most CAD systems have black as the drawing workspace background color to reduce eye strain and physical exhaustion from staring for hours at a rendered model - user should have a choice as to workspace background color.  If it's already a set-able system property somewhere, I can't find it, so it should at least be documented.

### LINKED ISSUE #378: Overhaul web version
the desktop app has more and more features (keybindings, updated 3d viewer, settable options , clear seperation of side effects from the main logic etc) and the web version is lagging behind: time to update it, and to unify as much code as possible, putting a lot of common codebase into the 'core' package for re-use

### PR DESCRIPTION
**Pull request by kaosat-dev**
This is a major overhaul to the web package & core structure:
* side effects (http, file system, dom) are now clear , seperate entities
* require() support for client side is fully working & tested

This is a major upgrade of the web UI:
* combines / upgrades the web ui with the desktop advances (amongst other things)
   * updated 3D viewer
   * keyboard shortcuts
   * modules support
   * allow multiple instances of jscad per page easilly
   * very simple api for embeding a jscad instance
   * completely restructured internals
   * maximized reuse of code between uis
   * lots more !!

# What this does and does not

## inputs
- [x] drag and drop of files
- [x] drag and drop of folders
- [ ] loading of remote files
- [ ] conversion of files
- [x] require support , injection of explicit api
- [x] require support , geometry caching 
- [x] require support relative paths
- [ ] require support node_modules (drag & drop)
- [x] require support single file
- [x] file watcher/autoreload for single file
- [x] file watcher/autoreload for folders
- [x] examples
- [x] virtual fs module injection ie allow const fs = require('fs') in the browser

## outputs
- [x] save/export of files using v2 api

## error handling
- [x] fix unhandled and explicit error handling
- [x] make error handling from different sources coherent (web worker, http requests etc)
- [x] fix handling of http request errors 4xx
- [x] fix handling of http request errors (all)

## 3D viewer
- [x] 3d viewer basics
- [ ] zoom to fit settable
- [ ] no resseting of camera to previous state
- [x] all 3D viewer instances should behave independantly
- [x] improve rendering of 2d lines (no lighting)

## code editor
- [ ] code editor basics
- [ ] code editor autocomplete

## ui
- [x] shortcuts
- [x] theming
- [ ] styling
- [ ] variations: min
- [ ] variations: opts ??

## general
- [x] examples jscad (old style)
- [ ] examples jscad updated to new explicit import api
- [x] translations
- [x] multiple instances per page
- [x] coherent input/outputs handling
- [x] correct timeout and geometry generation cancelation
- [x] correct error displaying

## tests
- [ ] side effects

## docs
- [ ] general
- [ ] observables
- [ ] specifics
- [ ] how to create instances
 
## final checklist if all the above is done
- [ ] work in chrome
- [ ] work in firefox
- [ ] work in safari
- [ ] work in brave
- [ ] works on mobile (?)
- [ ] proxy

closes #119 
closes #137 
closes #167 
closes #235 
closes #245 
closes #321 
closes #327 
closes #336 
closes #343 
closes #344 
closes #364 
closes #378 

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Does your submission pass tests?

> Note: please do NOT include build files (those generate by the build-xxx commands) with your PR,

Thank you for your help in advance, much appreciated !

### CODE REVIEW

**Comment by z3dev** [comment]
Just keep in mind that anything that changes for the users needs to have some documentation. I’m excited to see the changes but there is a growing user base. With fame comes responsibility... ask Mark Zukerburg.

**Comment by z3dev** [comment]
@kaosat-dev this is looking good.
Let me know if some testing can be performed, especially across some of the browsers.

**Comment by relatingdata** [comment]
conflicts?

**Comment by kaosat-dev** [comment]
hi @z3dev I both agree and not :) 
You are right that this is a way too big PR, but also just looking at the git changes is not a good fit for a rewrite, so it is normal that it is hard to look at it from that angle.
I have a few things to finish fixing before moving on, but will merge to V2 after that.

**Comment by z3dev** [comment]
@kaosat-dev Great. I’ll be patient.

Maybe we can ask to contribute t9 the V2 branch once a available. :)

**Pull request merged**
