### PR TITLE
fix(modeling): use modern typescript imports

### PR DESCRIPTION
**Pull request by platypii**
This PR updates V3 branch to fix a ton of type errors. Also a bunch of jsdoc cleanup. Typescript uses jsdoc for type hints, so they are related.

Changes include:

 - Use explicit file extensions when doing `import type ... from './type.d.ts'` files
 - Change `import { Geom2 }` to `import type { Geom2 }`. Why? Because modern typescript requires adding "type" in order to stay compatible with ES modules.
 - Always use capital `Geom2`, `Geom3`, `Poly3`, etc when used as a type
 - Change `Number`, `Float`, `Integer` to `number`
 - Change `String` to `string`
 - Remove unnecessary typedefs
 - Remove unnecessary namespaces
 - Add tsconfig.json file to configure typescript
 - Add global.d.ts with basic geometries and maths so that they can be used in jsdoc without importing explicitly
 
Note: this doesn't fix all the type errors, that's a bigger project. But this helps fix a lot of them. My goal is to have good autocomplete for JSCAD, and having good types really helps with that.

Sorry for the huge PR!

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Does your submission pass tests?

### CODE REVIEW

**Comment by hrgdavor** [comment]
nice work !

**Comment by z3dev** [comment]
@platypii did you sleep the last few weeks?

i'm not really interested in reviewing 697 files. UGG

is there anything specific that you would like reviewed?

**Comment by platypii** [comment]
> @platypii did you sleep the last few weeks?
> 
> i'm not really interested in reviewing 697 files. UGG
> 
> is there anything specific that you would like reviewed?

Sorry. I can try to split it up into multiple PRs if you prefer? Basically it's all just syntax changes on the types. Most of if was search-and-replace across all files. I tried to be pretty careful. So, if you want to approve, I'm happy to fix any bugs that come up in the future.

**Review by z3dev — APPROVED** [review]
@platypii this is a huge amount of changes. thanks for making these changes.

as mentioned, further changes may be necessary but this will be a great starting place for improvements. thanks again.

**Pull request merged**
