### PR TITLE
feat(modeling): reworked vectorChar and vectorText to return segments as path2 objects

### PR DESCRIPTION
**Pull request by z3dev**
These change rework both vectorChar and vectorText to convert font segments into path2 objects. This allows the font outlines to be used directly in other functions.

Actually, the results are not lists of path2 objects, but rather lists of vectorChar and vectorText objects (anonymous), and the vectorChar object has a list of path2 objects.

Some subtle bugs were corrected as well, which included the use of letterSpacing and lineSpacing.

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Does your submission pass tests?

### CODE REVIEW

**Comment by z3dev** [comment]
@platypii @hrgdavor please look over these changes.

the vectorChar and vectorText functions return anonymous objects still, as there's some useful information provided about height and width. if not useful then just list of path2 objects can be produced.

**Comment by hrgdavor** [comment]
> useful information provided about height and width.
I am for keeping that info. I am guessing it is needed to place them correctly ?

**Review by hrgdavor — APPROVED** [review]
looks good :)

**Comment by z3dev** [comment]
@rozek You may be interested in these changes. If you have time then please take a look. All comments are welcome.

**Pull request merged**
