### PR TITLE
refactor(all): use named import/export for ES modules

### PR DESCRIPTION
**Pull request by platypii**
This is what it would look like if we got rid of all the `export default` in the V3 branch, and instead use named import/exports for everything.

I think it's a good best practice. Instead of there being two ways to do something, this makes it so that we are consistent in always doing it one way. No need to think about how to import or export. This removes the need to add "export default" at the bottom of each file, so it saves hundreds of lines of code. It feels like cleaner use of ES modules.

Everything is exactly the same for users. The exported API doesn't change at all. This just simplifies how modules are imported internally in the codebase.

Let me know what you guys think.

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Does your submission pass tests?

### CODE REVIEW

**Comment by z3dev** [comment]
@garyhodgson what do you think?

personally, I like simple concise code. Which makes maintenance far easier.

@platypii is there a way to configure JSLint to flag default exports?

**Review by z3dev — DISMISSED** [review]
@platypii thanks for the massive amount of cleanup. the indexes look really clean now as well.

in general, i think these changes improve the code by simplifying the exports, adjusting code to follow the same style, and eliminating a whole lot of redundant wasteful code.

Any last comments before I merge?

**Comment by platypii** [comment]
Just pushed some last minute cleanup of the imports. I think it's good now.

There is an ESLint rule `no-default-export` that we could set, but eslint appears to not be setup currently?

**Comment by z3dev** [comment]
> Just pushed some last minute cleanup of the imports. I think it's good now.
> 
> There is an ESLint rule `no-default-export` that we could set, but eslint appears to not be setup currently?

The basic rules are from sandardx but additional rules can be set. See package.json

**Comment by platypii** [comment]
Added lint check. Also made some more updates: updated import/port for packages outside of modeling, and removed default exports from typescript .d.ts files.

**Comment by z3dev** [comment]
reviewing... but there's a lot of file... ;)

**Review by z3dev — APPROVED** [review]
@platypii THAT WAS MASSIVE!!!

**Comment by z3dev** [comment]
@platypii anything else pending? if not then i will merge.

**Comment by platypii** [comment]
Yup looks good!

**Pull request merged**
