### PR TITLE
style(web): css tweaks

### PR DESCRIPTION
**Pull request by platypii**
Minor clean up and fixes to CSS

- Remove unused big.css, min.css, openjscad.css files
- ~Remove unimplemented "file handling" option~
- Fix padding on "Load a JSCAD project" button
- Fix #controls and #header elements overflowing the page width
- Add semi-transparent background to option menus
- Fix padding of fieldsets in options menu
- Use max-height instead of height so that menus aren't larger than necessary
- Full height on code editor

Hopefully not controversial changes, just little UI improvements. Tested on chrome and firefox, desktop and mobile.

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Does your submission pass tests?

### CODE REVIEW

**Comment by z3dev** [comment]
UG... CSS... UG... Which browsers did you test with? I will try everything that I have available as well.

**Comment by platypii** [comment]
Tested on:
:heavy_check_mark: linux chrome
:heavy_check_mark: linux firefox
:heavy_check_mark: mac chrome
:heavy_check_mark: mac safari
:heavy_check_mark: android chrome

**Review by z3dev — CHANGES_REQUESTED** [review]
@platypii the CSS changes look fine.

I'm not sure about the elimination of the "File Handling" option. I know that it's not used but could be in the future. Also, there are other options that should be removed as well, e.g. Storage path. So, let's do these as part of another PR.

**Comment by platypii** [comment]
@z3dev I removed the "file handling" changes, now its just the css changes

**Review by z3dev — APPROVED** [review]
@platypii i tested the new CSS across the browsers. the UI looks cleaner now. thanks.

**Pull request merged**
