### PR TITLE
Document changes

### PR DESCRIPTION
**Pull request by z3dev**
A few documentation changes to correct some issues.

Also, new information links were added to the help of the WEB UI
- open issues
- discord community

### All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [X] Does your submission pass tests?

### CODE REVIEW

**Review by hrgdavor — DISMISSED** [review]
that was fast :) modifiers are now documented from jsdoc :) 
I just took  a quick look, but changes look good

**Comment by z3dev** [comment]
@hrgdavor thanks!

did you notice any other documentation errors?

**Comment by hrgdavor** [comment]
I have not. This one came-up today while discussing a fix for booleans.

**Comment by z3dev** [comment]
> I have not. This one came-up today while discussing a fix for booleans.

OK.

FYI, I'm adding a link to 'Open Issues' via the 'Help' dialog.

Do you want to add the 'Discord Community'?

**Comment by hrgdavor** [comment]
This is a permalink to discord channel https://discord.gg/BVnJ27vgcD will you add it ? or should I make a PR ?

**Comment by z3dev** [comment]
> This is a permalink to discord channel https://discord.gg/BVnJ27vgcD will you add it ? or should I make a PR ?

I will add 'Discord Community' to Help in this PR. The link will be to ~/discord.html

During the release, I'll add the discord.html file which redirects to the discord channel URL. Magic!

**Review by hrgdavor — APPROVED** [review]
The changes look good :)

**Pull request merged**
