### PR TITLE
V3 Pre-relese Preparations

### PR DESCRIPTION
**Pull request by z3dev**
These changes adjust the packages as well as the rollup configurations. All packages now rollup to complete self-enclosing libraries, minimal code with un-mangled names.

NOTE: No code logic was changed.

### All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [X] Does your submission pass tests?

### CODE REVIEW

**Comment by z3dev** [comment]
@platypii @hrgdavor sorry for another large set of changes. the packages are now ready for publishing. ;)

hopefully, i can publish V3 alpha releases in the next few weeks.

**Review by platypii — APPROVED** [review]
Looks good 👍

**Comment by hrgdavor** [comment]
@z3dev I would like to draw attention to one thing:
I am personally for moving away from automagic require('') loading STL or other formats, but it will continue to be fully supported for jscad V2 scripts in new jscad prototype. I prefer for V3 code to be as close to a regular js project, so idea is to make jscad io easily usable in any js project, not just jscad scripts. I am working on `input type=file` and from first attempts jcad/io ergonomy is bit awkward.

ideally a script would `import {deserialize} from '@jscad/io'` or more specific `import {deserializeStl} from '@jscad/io'` and then
```js
import {deserialize} from '@jscad/io'
export const main({inputFile, numOfSlices=10}){
  const object = deserialize(inputFile.name, inputFile.content)
  // return sliced object
}
```

that way such script could be used in nodejs
```js
import {readFIleSync} from 'fs'
import * as slicer from './slicer.js'

const name = process.argv[1]
const content = readFileSync(name)
const sliced = slicer.main({inputFile={name,content}})
// do something with sliced object

```

**Comment by z3dev** [comment]
> @z3dev I would like to draw attention to one thing:

@hrgdavor Not sure why this was added to a closed merge request.

Wouldn't this be best as a discussion point? These ideas are going to get lost very soon.

**Comment by hrgdavor** [comment]
@z3dev I was eager to make the point. I will create a discussion page. We should look more into API from a perspective of how we would like to write jscad scripts more easily. ... copied the comment to #1289 discussion

**Pull request merged**
