### PR TITLE
style(all): run standardx --fix

### PR DESCRIPTION
**Pull request by platypii**
JSCAD linter `npm run lint` uses the `standardx` package, which has an option `npx standardx --fix` which will automatically fix some of the lint errors. I ran that against the codebase. There is also some additional minor linting I did by hand.

The result is a huge reduction in lint errors `npm run lint | wc -l`:
master: 496
branch: 78

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Does your submission pass tests?

### CODE REVIEW

**Comment by z3dev** [comment]
@platypii not wrong but VTREE and DESKTOP are not being used today. DESKTOP will be replaced by the new viewer being developed by @hrgdavor, and that may require VTREE.

Also, VTREE needs a lot of work to bring it up to date, test, and release. Please don't waste effort on this package until necessary.

are you sure these changes are worth the effort?

**Comment by platypii** [comment]
I think the vtree stuff is a really cool idea (even if it doesn't work today). So I hope that vtree gets revived.

And I don't really care about the desktop package, but I do care about fixing lint errors. Fixing these will help us to focus on the remaining lint errors, and that might help us to catch bugs.

So I still think it's worth the effort (plus I already did the effort :smile:).  But if you have alternate ideas for this, just let me know, i won't be offended.

**Comment by z3dev** [comment]
Clean code is awesome! :)

I just don't want you to get bored. There are plenty of fun things to do, like rewriting 3D expansion/offset, etc.

**Review by z3dev — APPROVED** [review]
I have no idea if these changes will ever be of value…

**Pull request merged**
