### PR TITLE
V2 : simple test suite for cli

### PR DESCRIPTION
**Pull request by z3dev**
These changes simplify the test suite for CLI, using only a simple built-in script. There are now two test suites

- test suite to verify all parameters to CLI
- test suite to verify simple conversions via CLI

NOTE: The previous test suite using @jscad/examples has been disabled. The examples should be verified / tested seperately.

### All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [X] Does your submission pass tests?

### CODE REVIEW

**Comment by z3dev** [comment]
@kaosat-dev please review.

I created some simple test suites based on the previous test suite, but simplifying the tests and removing any dependencies.

**Comment by kaosat-dev** [comment]
@z3dev I am on this, still quite torn to be honest, I like the added simplicity , but loosing the use of examples as inputs for cli is both a blessing & a curse (simpler, but also makes us loose auto validation and re-use of assets)

**Comment by z3dev** [comment]
@kaosat-dev understood. you can enable the test which uses the examples once ready. these simple tests will make sure that options, etc work as expected.

**Comment by z3dev** [comment]
@kaosat-dev any further changes? questions? approve?

**Comment by kaosat-dev** [comment]
yes, I'll try to finish my review/ tweaks tomorrow, sorry !

**Comment by z3dev** [comment]
@kaosat-dev please merge. as mentioned. you can enable the test suite that uses the examples later. Or (even better), you can create a test suite for the examples that uses the CLI.

**Pull request merged**
