### PR TITLE
use isIdentity

### PR DESCRIPTION
**Pull request by hrgdavor**
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Does your submission pass tests?

improve no-op check
 - avoid creating a new matrix just to check if it is a no-op matrix

### CODE REVIEW

**Comment by z3dev** [comment]
@hrgdavor Obviously, we are headed in the same direction. :)

Can you review #865 pull request? I think that has a slightly name for the new comparison function. (I did some DOC changes as well, as the math documentation was kind of sick.)

After #865 is merged to master, you can sync and update the geometry code to use the new function.

**Comment by z3dev** [comment]
Hmm... why did the build fail?

**Comment by hrgdavor** [comment]
> Hmm... why did the Travis CI fail?

I forgot to add it to index.js 😄 

> After #865 is merged to master, you can sync and update the geometry code to use the new function.

yes, np :)

**Comment by hrgdavor** [comment]
> After #865 is merged to master, you can sync and update the geometry code to use the new function.

updated to use `isIdentity`, should be ok to merge now

**Review by z3dev — APPROVED** [review]
Good! Thanks for following up with these changes.

**Pull request merged**
