### PR TITLE
clone utility

### PR DESCRIPTION
**Pull request by hrgdavor**
related to #856 

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Does your submission pass tests?

I have added a check if the cloned object has it's own clone function, but I think it is not necessary yet, and can easily be added later on.

I have applied standardx, but no idea what to test if even necessary for such basic code.

### CODE REVIEW

**Comment by z3dev** [comment]
This is a great start but there are some issues with this approach.

First, this doesn't guarantee that the resulting object (geometry) is **immutable**, which is required throughout the design of the library. For example...
```
let a = cube()
let b = clone(a) // b now has the guts of a
let c = geom3.toPolygons(b) // or geom3.applyTransforms(b)
```
After the toPolygons, b has new polygons, and b reset transforms to mat4.identity. However, a has the old polygons still, BUT the transforms have been changed as well to mat4.identity(). There's a small change required in the applyTransform function of the geometries.

NOTE: geom3.toPolygons(), geom2.toSides(), path2.toPoints() is being called often throughout the libraries.

Second, a utility function is fine, and it might be used by the geometries. However, adding the utility function to the utilities API means that users can call this without worry. That's not the case currently. So, this new functionality might be better as part of the geometries, such as cloneShallow().

My suggestion is that geom3.clone(), geom2.clone(), and path2.clone() all produce 'deep' copies of the guts. And a new function is added to all geometries to 'extend' or 'mutate' or 'tweek' attributes. For example...
```
let a = cube()
let b = colorize([1, 0, 1], a) // and this calls geom3.tweek({ color: [1, 0, 1] }, a)
```
The colorize function is a good example, where the guts of the geometry are retained, and a new attribute 'color' is added.

**Comment by hrgdavor** [comment]
I will look into these issues in more detail. 

Here are my initial thoughts:

A better approach is to fix the offending methods so that shallow clone remains safe. 
I am willing to assist in that direction.

Using deep-cloning just to play defensive/safe will inflict big performance hits very easily.

Clone utility is meant for advanced users that must be aware to not break immutability.

On the other hand, from what I understand by looking at the code... 
This clone utility would not be any less safe than translate, as even after translate(geom3) one could break the geometry(by messing with polygons data) that would affect other copies.

This inital PR is part of a push for geometries to remain usable (with extended functionalities) at least after doing basic operations like transform and colorize.

It is a line of thinking that came out of the proposal for new connectors.

**Comment by hrgdavor** [comment]
I have created a pull request to address the mutability of the applyTransforms #866

I hope this direction is acceptable.

**Comment by hrgdavor** [comment]
Closed in favor of fresh attempet to bring immutability into the core

**Pull request closed without merging**
