### PR TITLE
V2: Missing variable declaration

### PR DESCRIPTION
**Pull request by RedHatter**
Missing variable declaration causing failure in strict mode.

### CODE REVIEW

**Comment by z3dev** [comment]
@RedHatter how did you catch that? Did you run node with strict mode?

**Comment by RedHatter** [comment]
I'm running it in a program built with rollup. In particular I found this error by running in chrome with 'use strict' at the top of the file.

**Comment by RedHatter** [comment]
Sorry, wrong button

**Comment by z3dev** [comment]
Hanks. There are probably other oversights in the code. It’s probably better to fix all the lint errors. But that will be a slightly larger effort.

**Comment by kaosat-dev** [comment]
Thanks for the fix @RedHatter !
@z3dev this is small & fast to merge, shall we ?

**Comment by z3dev** [comment]
@kaosat-dev sure. Looks fine.

**Pull request merged**
