### PR TITLE
Vtree integration

### PR DESCRIPTION
**Pull request by kaosat-dev**
# All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Does your submission pass tests?

> Note: please do NOT include build files (those generate by the build-xxx commands) with your PR,

Thank you for your help in advance, much appreciated !

### CODE REVIEW

**Comment by z3dev** [comment]
😃

**Comment by kaosat-dev** [comment]
woot ! Tests are passing for the pr :)

**Comment by z3dev** [comment]
> woot ! Tests are passing for the pr :)

sweet!

**Comment by kaosat-dev** [comment]
@z3dev if you are ok, I will merge this, it ONLY merges VTREE into the main repo and cleans some minor things up, but does NOT make it up to date with V2 (that is another PR).
It should finally fix our failing build though :)

**Comment by z3dev** [comment]
> @z3dev if you are ok, I will merge this, it ONLY merges VTREE into the main repo and cleans some minor things up, but does NOT make it up to date with V2 (that is another PR).
> It should finally fix our failing build though :)

I’m fine with the merge but there’s a lot to digest. I’d like to add a few comments first. Is that fine?

**Comment by kaosat-dev** [comment]
@z3dev sure, but I will not make any significant changes to keep the PR limited in scope

**Comment by kaosat-dev** [comment]
ahh also : this PR integrates the whole commit history of the previous VTREE repo, there are only a few  specific commits

**Comment by z3dev** [comment]
> ahh also : this PR integrates the whole commit history of the previous VTREE repo, there are only a few specific commits

In that case, please merge as changing merges is a pain in GIT. I will add comments later.

**Pull request merged**
