### PR TITLE
V2 : cleanup color api

### PR DESCRIPTION
**Pull request by z3dev**
These changes enchance the conversion functions to use spread parameters, allowing the functions to accept both arrays of values or a list of values.

In addition, a few adjustments to doc strings were made.

### All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [X] Does your submission pass tests?

### CODE REVIEW

**Comment by kaosat-dev** [comment]
this is awesome @z3dev ! Any other changes, or is the PR ready ?

**Comment by z3dev** [comment]
@kaosat-dev please merge if the changes are fine. I’d be glad to make further changes as well.

**Comment by kaosat-dev** [comment]
@z3dev not sure I understand ? Do you want to make further changes ?

**Comment by z3dev** [comment]
Nope. no more changes. I like these changes as it makes the API easier to use.

**Pull request merged**
