### PR TITLE
V2 Pre-release : 2020 OCT 24

### PR DESCRIPTION
**Pull request by z3dev**
Pre-release version of V2 JSCAD, including changes from several previous pull requests.

Bug Fixes:
**web:** allow other file types to be loaded into the fake FS of the WEB UI
**web:** improve tracking of rotate/pan/zoom changes (Thanks to @aaa)
**svg-deserializer:** corrected determination and processing of ArrayBuffer data

Successfully published:
 - @jscad/cli@2.0.0-alpha.9
 - @jscad/core@2.0.0-alpha.9
 - @jscad/io@2.0.0-alpha.8
 - @jscad/stl-deserializer@2.0.0-alpha.7
 - @jscad/web@2.0.0-alpha.11
lerna success published 5 packages

### All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [X] Does your submission pass tests?

### CODE REVIEW

**Comment by z3dev** [comment]
@SimonClark please review this release quickly, and merge if no issues.

FYI, the changes have been released to www.jscad.xyz

**Comment by SimonClark** [comment]
oh, damn, did I mess this up by merging the io improvements?

**Comment by SimonClark** [comment]
Nevermind, merging into pre-release.  Should be fine :)

**Review by SimonClark — APPROVED** [review]

**Comment by SimonClark** [comment]
or not. sorry.  I'm clearly not thinking well this morning, and don't have a clear picture of the release process.  perhaps we should chat at some point, and I can document the flow.  Either way, let me know if I botched things up.  at least git will always have our backs :)

**Comment by z3dev** [comment]
Should be fine.
I will write a release document and add into the project. There should be no mystery now.

**Pull request merged**
