### PR TITLE
chore(all): housekeeping on gitignore file

### PR DESCRIPTION
**Pull request by SimonClark**
Adding working folders to the .gitignore file for the new docs folder location, and the .idea IDE temp folder

### All Submissions:

* [ x] Have you followed the guidelines in our Contributing document?
* [ x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [ x] Does your submission pass tests?

### CODE REVIEW

**Comment by z3dev** [comment]
GAG
I thought there was only one .gitignore
Is there anyway to integrate these changes into to project level .gitignore?

**Comment by SimonClark** [comment]
> GAG
> I thought there was only one .gitignore
> Is there anyway to integrate these changes into the project level .gitignore?

Sorry, not sure I follow.  There is one .gitignore for the repo at the root level, right?

**Comment by z3dev** [comment]
> Sorry, not sure I follow. There is one .gitignore for the repo at the root level, right?

Correct. Git only needs one.
Extra .gitignore files just make management confusing.

**Comment by SimonClark** [comment]
> > Sorry, not sure I follow. There is one .gitignore for the repo at the root level, right?
> 
> Correct. Git only needs one.
> Extra .gitignore files just make management confusing.

ok, I think I understand what's going on.  GitHub seems to be implying that the .gitignore file being changed is in /packages/web/examples/ when in fact that is just the line before it.

There is only one .gitignore, and it's at the root.  Click on the line that says packages/web/examples, and it will show the context of the lines above.

**Review by z3dev — APPROVED** [review]
Cool. This is fine.

**Pull request merged**
