### PR TITLE
fix(modeling): add extrudeHelical type definition

### LINKED ISSUE #1260: extrudeHelical types missing from index.d.ts
While working on an editor using JSCAD, I noticed that the `extrudeHelical` function that I added a while back has its typing definition missing in the corresponding index.d.ts file.

I'll make a pull request to fix this.

### PR DESCRIPTION
**Pull request by Loosetooth**
Closes #1260 

Some typing definitions were missing.
Tests pass.

### CODE REVIEW

**Review by z3dev — APPROVED** [review]
@Loosetooth Thanks. Keep those changes coming!

FYI, we use conventional commits to manage changes. If the titles are in the correct format then Lerna will append the titles to CHANGES.md for each package. All automatic.

https://github.com/jscad/OpenJSCAD.org/wiki/Admin-:--Merging-Pull-Requests

**Comment by Loosetooth** [comment]
Would you like me to bump up the version too, @z3dev ?

**Review by hrgdavor — APPROVED** [review]
looks good.

**Comment by z3dev** [comment]
> Would you like me to bump up the version too, @z3dev ?

I'll try to cut a new version tomorrow. It was a bit hectic today.

**Review by platypii — APPROVED** [review]
Good catch thanks

**Pull request merged**
