### PR TITLE
Uncaught Type Error in viewer.js in package Web #999

### PR DESCRIPTION
**Pull request by samuelwang48**
### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Does your submission pass tests?

> Note: please do NOT include build files (those generate by the build-xxx commands) with your PR,

Thank you for your help in advance, much appreciated !

### CODE REVIEW

**Review by z3dev — CHANGES_REQUESTED** [review]
@samuelwang48 please revert the change to the jscad-web.min.js library. this is rebuilt during the release process, and shouldn't be part of code changes. thanks

you can just copy the latest from 'master', and commit that version. that should remove these changes.

**Comment by samuelwang48** [comment]
> @samuelwang48 please revert the change to the jscad-web.min.js library. this is rebuilt during the release process, and shouldn't be part of code changes. thanks
> 
> you can just copy the latest from 'master', and commit that version. that should remove these changes.

Hi @z3dev the specific change aforementioned has been reverted. Feel free to let me know if there is anything else I can help. Thanks

**Comment by z3dev** [comment]
@samuelwang48 thanks for these changes, but i think another solution might be slightly better.

The viewer **only** supports the JSCAD geometries, so it's probably better just to filter the solids returned from the design, here... viewer.js, line 146

`    const solids = state.design.solids.filter((solid) => solid && (solid instanceof Object))`

Thoughts?

**Comment by samuelwang48** [comment]
> @samuelwang48 thanks for these changes, but i think another solution might be slightly better.
> 
> The viewer **only** supports the JSCAD geometries, so it's probably better just to filter the solids returned from the design, here... viewer.js, line 146
> 
> ` const solids = state.design.solids.filter((solid) => solid && (solid instanceof Object))`
> 
> Thoughts?

Hi @z3dev, Thanks! I've made the changes accordingly. The said issue seems to have been solved. All tests passed.

**Review by z3dev — APPROVED** [review]
@samuelwang48 thanks. i hope this is the last time fixing this issue. ;)

**Pull request merged**
