### PR TITLE
Update scission.d.ts

### PR DESCRIPTION
**Pull request by FishOrBear**
Fix this return result.

### CODE REVIEW

**Review by platypii — DISMISSED** [review]
Good catch

**Comment by platypii** [comment]
Technically scission does not support Geom2 so that first line could actually be deleted...

**Comment by z3dev** [comment]
@FishOrBear technically, this is correct, however scission of geom2 is not performed, only the original geom2 objects are returned. Is that ok?

of course, if you submit the code for geom2 scission then we would be really happy.

**Comment by FishOrBear** [comment]
@z3dev ok, I have updated the code

**Review by z3dev — APPROVED** [review]
@FishOrBear looks fine. Thanks

**Pull request merged**
