### PR TITLE
perf(web): changed to retain webworker process

### PR DESCRIPTION
**Pull request by z3dev**
While working through some issues with rollup, I came across issues with the webworkify package. (It can only be packaged using Browserify. 😢  ) However, I tried to retain the webworker instead of terminating / initializing. It works just fine across the browsers. In addition. error handling has been improved so processing should be more robust as well.

Performance improves differently across the browsers, but basically the 100 ms delay of creating a new webworker is gone.

Manually tested these changes across Safari, Firefox, Chrome, and Edge on MacOS 10.14.6
Also Safari, Firefox, Chrome, and Edge on IOS

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Does your submission pass tests?

### CODE REVIEW

**Comment by z3dev** [comment]
Please try these changes across as many browsers as possible.

**Review by platypii — APPROVED** [review]
Looks good. I tested on various browsers and saw typical improvements of 60-80ms per model load. Awesome!

Tested on:
 - linux chrome
 - linux firefox
 - mac m1 chrome
 - mac m1 firefox
 - mac m1 safari

Since we are persisting the web worker, I also wanted to make sure that there wasn't a memory leak. I did this by updating the model repeatedly while monitoring memory usage. Even with large models, repeatedly loaded, the memory always freed back to baseline. :+1:

**Comment by hrgdavor** [comment]
I know it is already merged, but not sure if I should make a separate issue

I was curious about the terminate of the worker and details how it would behave, and I added for my test purpose console log when terminating or sending a command.

I used a boolean on 2 spheres with enough segments to make it last more than 1 second, then I clicked parameter few times. 3 commands were sent to worker, and were all executed, there was no cancel happening.


image

```js
const jscad = require('@jscad/modeling')
const { sphere } = jscad.primitives
const { subtract } = jscad.booleans
const { translate } = jscad.transforms

function main({ // @jscad-params
  segments = 32 // {step:8}
}){
  return subtract(
    sphere({}),
    translate([0,0.5,0.5],sphere({segments}))
  )
}

module.exports = {main}
```

**Comment by z3dev** [comment]
> I know it is already merged, but not sure if I should make a separate issue
> 
> I was curious about the terminate of the worker and details how it would behave, and I added for my test purpose console log when terminating or sending a command.
> 
> I used a boolean on 2 spheres with enough segments to make it last more than 1 second, then I clicked parameter few times. 3 commands were sent to worker, and were all executed, there was no cancel happening.
> 
> image
> 
> ```js
> const jscad = require('@jscad/modeling')
> const { sphere } = jscad.primitives
> const { subtract } = jscad.booleans
> const { translate } = jscad.transforms
> 
> function main({ // @jscad-params
>   segments = 32 // {step:8}
> }){
>   return subtract(
>     sphere({}),
>     translate([0,0.5,0.5],sphere({segments}))
>   )
> }
> 
> module.exports = {main}
> ```

What was the result of the viewer?

**Comment by hrgdavor** [comment]
all get executed
image

I uses sequence of segments and manual update: 208,8,208,8 and let it play out
 - 208 was being executed
 - 8 was queued
 - 208 queued
 - 8 queued
 - 208 finished
 - 8 finished
 - 208 finished
 - 8 finished

I intentionally took large difference to see visual changes. Clearly no cancel is happening if new command is supplied
I tried 308 segments and it executed for 50 seconds, and no cancel happened. So I am not sure when cancel is triggered. This could be an issue with code before this PR, it probably is not caused by your recent changes.

**Pull request merged**
