### PR TITLE
Improve svg rendering

### PR DESCRIPTION
**Pull request by z3dev**
These changes improve the 'rendering' of designs exported to SVG. 
- set defaults for fill, fill-rule, stroke-width at the SVG level
- remove above from path serialization
- corrected fill color for continuous paths (geom2)
- added support for special attributes; id and class

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Does your submission pass tests?

### CODE REVIEW

**Comment by z3dev** [comment]
@hrgdavor please review / try if you have time. I think these changes will help users when exporting to SVG.

**Comment by z3dev** [comment]
See #558 for how to add a ‘name’ to objects

**Comment by hrgdavor** [comment]
np. I will take a look a bit and test

**Comment by hrgdavor** [comment]
It will be few days before I can do so, I am traveling today and tomorrow, so I can't test this right away

**Comment by hrgdavor** [comment]
I have been playing with it, and it looks good in the svg source. I am not a fan of using fill.

While jscad renders lines
image

the svg export uses fill

image

personally I would prefer stroke
image

**Comment by hrgdavor** [comment]
I have some complaint/proposals that are unrelated to this PR.

jscad is generating poly for each curve immediately, so an export to SVG is a poly instead of circle, arc, besier.

Without changing jscad core, one option would be to explore integration with other 2d libs like maker.js ... actually all that is needed is to improve require in the future because V2 now allows us to script with any valid JS lib.

**Review by hrgdavor — APPROVED** [review]
It is a good step forward.

**Pull request merged**
