### PR TITLE
docs(modeling): fix spelling mistakes and typos

### PR DESCRIPTION
**Pull request by platypii**
Credit to JetBrains IDE for warning about these spelling and grammar mistakes.

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Does your submission pass tests?

### CODE REVIEW

**Review by z3dev — APPROVED** [review]
Wow! This is going to be the cleanest documentation on the planet!

**Comment by platypii** [comment]
@z3dev I added a commit to fix #1011. It seems like CI is stuck though.

**Review by z3dev — APPROVED** [review]
Let's do it.

**Comment by z3dev** [comment]
FYI... JSCAD ran out of build credits at Travis CI. Hopefully, the will provide free credits to proceed. Hold on...

**Comment by z3dev** [comment]
> If you wish, I can create a PR to add Github actions. They will be more reliable than Travis CI.

Oh man! That would be awesome! I was thinking the same but can’t find the time.

**Comment by z3dev** [comment]
@platypii please merge the latest from master. i don't think there will be any surprises. just some conflicts to resolve.

**Review by z3dev — APPROVED** [review]

**Pull request merged**
