### PR TITLE
V2 : Enable JSDOC

### PR DESCRIPTION
**Pull request by z3dev**
This pull request enables JSDOC as a common tool across all packages.
- configuration file; jsdoc.json
- script added to package.json
- updates to modeling source code to:
  - give each exported function a name space (alias) in documents
  - corrections to eliminate JSDOC errors
  - additions to give each function some kind of documentation

**THERE ARE NO CODE CHANGES**

### All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [X] Does your submission pass tests?

### CODE REVIEW

**Comment by z3dev** [comment]
@kaosat-dev please try the document generation out.

you'll have to checkout this branch, and run npm install. the generated documents (HTML) will be found in the out directory.

there are so many options to JSDOC, so I wanted to start somewhere. i think the documentation is very good now (after the large number of doc string changes). the configuration is using a template called 'docdash', and formats very nice documents.

and, yes, there could be both markdown and html documents.

**Comment by kaosat-dev** [comment]
@z3dev Thanks for this, looking awesome so far !
This will take me a bit more time to review , I'll post back once I am done with local testing

**Comment by z3dev** [comment]
@kaosat-dev this is ready to merge.

it added doc strings for the to/fromCompactBinary functions. :)

also, i raised a new issue with docdash, requesting to have an option to remove the 'static' on documentation.

**Comment by z3dev** [comment]
@kaosat-dev please approve and merge.

**Pull request merged**
