### PR TITLE
Camera fix

### PR DESCRIPTION
**Pull request by jallwine**
Decoupled zoom and viewpointZ and fixed touch/mouse events to properly shift the camera.

### CODE REVIEW

**Comment by z3dev** [comment]
@jallwine thanks for the nice changes.

fyi, release 0.5.2 is in progress already, which includes testing. so, i'm not sure these changes will get into 0.5.2 or not.

just for a sanity check, did you test all the examples with these changes? that's the lint test for all changes.

**Comment by jallwine** [comment]
Not all of them, just a couple of my own and the default example. I didn't touch anything that would be different for different examples. This change just makes sure the camera is rotating about the point you're looking at, whereas currently when you rotate you're always rotating about the origin.

**Comment by jallwine** [comment]
You can see it in action here: http://www.allwinedesigns.com/blog/work-table

**Comment by z3dev** [comment]
@jallwine Could you reapply your changes to the new restructured source code? It would be a great help, and allow testing to be completed.

**Comment by jallwine** [comment]
Yeah, I'll do my best to find some time soon. I've been meaning to check out how everything was restructured.

**Pull request closed without merging**
