### PR TITLE
feat(web): enhanced to support auto zoom control

### PR DESCRIPTION
**Pull request by z3dev**
These changes enhance the WEB UI to support auto zoom. The changes are:
- create auto zoom control (and remove zoom options)
- update most streams to support setting of auto zoom control
- update view to support auto zoom control
- update locales for languages

### All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [X] Does your submission pass tests?

> Note: please do NOT include build files (those generate by the build-xxx commands) with your PR,

Thank you for your help in advance, much appreciated !

### CODE REVIEW

**Review by z3dev — COMMENTED** [review]
Changes as expected.

**Comment by z3dev** [comment]
@ hrgdavor how about adding a review of these changes? You should be able to run this locally by pulling the latest changes, and checking out 'fix-auto-zoom' branch.

**Review by hrgdavor — COMMENTED** [review]
Works well on windows, Chrome and Firefox, Edge.

Personaly I would prefer tightness of autozoom closer to 1. I tried tightness:1.1 and it still leaves plenty of space, but is ofc closer to the camera.

**Comment by z3dev** [comment]
> Works well on windows, Chrome and Firefox, Edge.
> 
> Personaly I would prefer tightness of autozoom closer to 1. I tried tightness:1.1 and it still leaves plenty of space, but is ofc closer to the camera.

OK. I'll try out a little tighter zoom setting. If nothing looks strange / cut off then I'll make another change. Thanks.

**Review by mister-jscad — APPROVED** [review]
Looks good.

**Pull request merged**
