### PR TITLE
fix(modeling): types for measurement functions

### PR DESCRIPTION
**Pull request by atkinchris**
This adds missing TypeScript definitions for functions, and exports these through the `measurements` type index.

The missing types added are for:

- `measureDimensions`
- `measureBoundingSphere`
- `measureCenter`
- `measureCenterOfMass`

### CODE REVIEW

**Review by z3dev — APPROVED** [review]
@atkinchris thanks for taking the time to submit the fixes. super.

**Review by platypii — DISMISSED** [review]
Looks good, nice catch

**Comment by platypii** [comment]
It appears that other missing definitions include:

- `measureBoundingSphere`
- `measureCenter`
- `measureCenterOfMass`

**Comment by atkinchris** [comment]
I've added the additional three, and matched their overloads to one another.

**Review by platypii — APPROVED** [review]
Awesome, thanks @atkinchris for the nice fixes!

**Comment by z3dev** [comment]
@atkinchris thanks again for the nice fixes!

**Pull request merged**
