### PR TITLE
Github Actions

### PR DESCRIPTION
**Pull request by t1u1**
This runs `npm install` and `npm test` on 3 different versions of node: 12, 14, 16

Is there anything else required as part of CI?

We could add `npm publish` for snapshots in the future, but that will require setting up auth keys in Github.

### CODE REVIEW

**Comment by t1u1** [comment]
As I am a first time contributor to this repo, Github actions will not be triggered automatically on this PR. An admin will have to manually trigger them.

**Comment by z3dev** [comment]
> This runs `npm install` and `npm test` on 3 different versions of node: 12, 14, 16
> 
> Is there anything else required as part of CI?

Actually, there are three steps
- npm install
- npm run bootstrap
- npm test

Thanks again

**Comment by platypii** [comment]
Why is `lerna bootstrap` needed? Tests seem to work without it.

**Comment by z3dev** [comment]
> Why is `lerna bootstrap` needed? Tests seem to work without it.

Good point. So, this should be fine.

**Comment by t1u1** [comment]
@z3dev Are you seeing the button in this PR to trigger the action?

> > Why is `lerna bootstrap` needed? Tests seem to work without it.
> 
> Good point. So, this should be fine.

This made me wonder, how do we ensure that the tests are running correctly. So I made a commit that deliberately breaks the code a bit to see if CI is able to catch it and then rolled back the bad commit. Confirmed to be working fine!

Here are the results on the forked repo: https://github.com/t1u1/OpenJSCAD.org/actions

**Comment by z3dev** [comment]
We just received credits to resume Travis CI. I'll merge this into the main stream this weekend when I have time to watch, and fix issues if any.

**Review by z3dev — APPROVED** [review]
Let's give this a shot...

**Pull request merged**
