### PR TITLE
V2 : Rewrite of reTesselateCoplanarPolygons

### PR DESCRIPTION
**Pull request by z3dev**
**WORK IN PROGRESS. DO NOT MERGE.**

This is a total rewrite of the reTesselateCoplanarPolygons() function. This version does not create new points, instead merges opposing polygons using the original points.. As such, the precision of all points is respected (This also means the other boolean functions must improve.)

Improved test suites for reTesselateCoplanarPolygons() are included.

### All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [ ] Does your submission pass tests?

### CODE REVIEW

**Comment by z3dev** [comment]
@kaosat-dev this is a BIG one. please look over the code when you have time. all comments are welcome.

**Comment by kaosat-dev** [comment]
@z3dev sure ! looks hefty ! will take a close look

**Comment by kaosat-dev** [comment]
first very broad comments: (I only had a very superficial glance so far)
- looks very clean, kudos !
- > This version does not create new points, instead merges opposing polygons using the original points

I understand the logic behind what you are shooting for, but I  think that could cause some serious issues: normally a **(re)tesselation** whole purpose is to generate **more / different triangles,** and thus points. Merging multiple pre-existing points/polygons is a different operation. (I cannot recall the name right now, but there was something like this in V1 I think ?)

**Comment by kaosat-dev** [comment]
I could be wildly off based on the function name, so I need to dig deeper though

**Comment by z3dev** [comment]
I can see why the name of retesselate was chosen. It’s because the old algorithm transformed all the points to 2D, and then built polygons by merging edges. This is the definition of tessellation.

However, any transform of points causes precision errors. And going from 3D to 2D to 3D causes bad things to happen.

**Comment by z3dev** [comment]
I'm closing this pull request, as this can be addressed AFTER the release of V2.

**Pull request closed without merging**
