### PR TITLE
Add hotkey to clear localStorage

### PR DESCRIPTION
**Pull request by alexose**
Addresses #267.  Kind of cheesy, but hopefully it'll be helpful to someone.

For Hacktoberfest :)  (hacktoberfest.digitalocean.com)

### CODE REVIEW

**Comment by z3dev** [comment]
@alexose Thanks!

We will definitely review.

**Comment by kaosat-dev** [comment]
Hi @alexose Thanks a lot for the PR ! :)
I am sorry to bother you with this but could you please remove the build files from the PR ?
Build files should not be included in PRs they are automatically generated with each new release: not your fault, we still need to  amend the README to make that more clear.
Thanks in advance !

**Comment by alexose** [comment]
No trouble at all.  I actually went back and forth on whether I should include the build files or not... guessed wrong!  :P

**Comment by kaosat-dev** [comment]
haha , we were also on the fence for a while , but it is simpler and more reliable this way !
Thanks for the changes and the PR !

**Pull request merged**
