### PR TITLE
fix(modeling): revert measureBoundingBox to only cache per geometry

### PR DESCRIPTION
**Pull request by z3dev**
As the title says.. sigh

### All Submissions:

* [X] Have you followed the guidelines in our Contributing document?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [X] Does your submission pass tests?

### CODE REVIEW

**Comment by z3dev** [comment]
@hrgdavor please review.

i hate to revert but think that there's some conflicts in the cache look up; by geom VERSUS by points.

alternatively, if a test case can be created then a fix may be possible.

i submitted this because i have no time to dig deep into this.

**Comment by hrgdavor** [comment]
@z3dev I will check if test case is possible and fix first.

**Comment by z3dev** [comment]
> @z3dev I will check if test case is possible and fix first.

@hrgdavor please check that measureBoundingBox is correct before and after cloning / transforming shapes. Maybe a new test case is required.

 I believe that allocation of a new bounding box is required when reusing the cached bounding box. In other words, the original bounding box should not be changed if coached.

**Review by mister-jscad — APPROVED** [review]
Looks fine. :(

**Pull request merged**
