### PR TITLE
docs(modeling): add docs describing geometries, paths, and polys

### PR DESCRIPTION
**Pull request by platypii**
I find it hard to remember the differences between geom, paths, and polygons. So I made some docs that makes for a easy reference. I put it in the jsdoc so that it would appear in the API Reference. If you think this belongs elsewhere, let me know.

Screenshot at 2022-02-19 13-49-39

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Does your submission pass tests?

### CODE REVIEW

**Comment by z3dev** [comment]
@platypii These little notes are nice. There are also notes for each geometry (see index.js)

There may be some useful notes from the User Guide as well.

https://openjscad.xyz/dokuwiki/doku.php?id=en:design_guide_path

**Comment by z3dev** [comment]
I added the following to geometries/index.js, which makes links directly to the specific geometry documentation. This seems like a good alternative.
```
 * @see geom2
 * @see geom3
 * @see path2
 * @see poly2
 * @see poly3
```

**Comment by platypii** [comment]
@z3dev I like that approach. Would you like me to refactor this branch to look like that? I can move my examples from `geometries/index.js` to `geometries/*/index.js`. Should I wait for you to push the changes you made? Or would you rather just include the `@see` links and leave examples for the wiki?

**Comment by z3dev** [comment]
> @z3dev I like that approach. Would you like me to refactor this branch to look like that? I can move my examples from `geometries/index.js` to `geometries/*/index.js`. Should I wait for you to push the changes you made? Or would you rather just include the `@see` links and leave examples for the wiki?

Great! Please refactor. Thanks

**Comment by platypii** [comment]
Refactored. I like this way much better, good call.

**Review by z3dev — APPROVED** [review]
Nice!

**Pull request merged**
